nand2tetris/web-ide

src/pages/chip.ts, src/simulator/chip/builder.ts, src/simulator/chip/builtins/index.ts, src/simulator/chip/builtins/logic/and.ts, src/simulator/chip/builtins/logic/not.ts, src/simulator/chip/builtins/logic/or.ts, src/simulator/chip/builtins/logic/xor.ts, src/simulator/chip/chip.ts
1. Change `getBuiltinChip` from Chip|never to Result<Chip>
2. When loading with a missing chip, start with `Low` and then attempt to parse saved data.
3. Add Or16 (a common project chip) to Builtins (and also Xor16)
4. Normalized return values for And16, Or16
5. (Misc) Added busVoltage to TrueBus and FalseBus
=> Gracefully handle missing Builtins.

README.md
Both links in the doc were broken.
I fixed the first one, while the second guide cannot be linked to (I tried, didn't work for some reason) and so I replaced the link with a link to the project and details on how to open the guide.
=> Fixed links to the user guide

src/components/pinout.tsx, src/pages/chip.store.ts, src/pages/chip.tsx
The clock is considered global, so we don't want it as a pin chip.
Closes #131
=> Move clock buttons to Chip header.

web/src/components/difftable.tsx, web/src/components/pico/pico.scss
Only show errors for completed out lines. 
Show errors stacked in a single cell.
Closes #127 
A passing diff table
A diff table with failures
For scrolling the table, I think this is the best we're going to get from the web layout. Having the flexible panels in VSCode will be a plus.
=> Diff table feedback

components/src/stores/chip.store.ts, web/src/pages/chip.tsx
Correctly reset tests when toggling built-in chip.
=> Track whether the chip store is or is not using the built in chip.

components/src/stores/chip.store.ts
=> Always load the new chip, then switch to the builtin if necessary.

.npmrc, package-lock.json, package.json
Since this project uses workspaces it requires npm 7 or greater. This can take time to figure out if you don't know it. This change causes you to set npm to the appropriate version if you try to use an incorrect version within the project, e.g. when installing with `npm install`
I specified node>=16 simply because npm seemed to think that was the required version when specifying npm>=7.
=> Specify and enforce node and npm requirements

projects/src/index.ts, projects/src/project_01/index.ts, web/src/App.tsx, web/src/versions.ts
Let me know what you think about the versioning to update the files automatically.
=> Rename Xor files to match chip name

components/src/stores/chip.store.ts, simulator/src/chip/builder.ts, simulator/src/languages/hdl.test.ts, simulator/src/languages/hdl.ts
This handles cases where the online IDE permits HDL code that is considered an error by the desktop java version.
=> Eliminate discrepencies between online IDE and desktop version

simulator/src/chip/builder.test.ts, simulator/src/chip/builder.ts
Chip implementation where both sides of a wire had different widths passed in the online IDE, but it should count as an error.
=> Enforce equal bus widths

simulator/src/chip/chip.test.ts, simulator/src/chip/chip.tsx
=> Fix check for wrapping with sub-bus

components/src/chips/screen.tsx, components/src/runbar.tsx, web/src/pages/cpu.scss, web/src/pages/cpu.tsx, web/src/pages/vm.scss, web/src/pages/vm.tsx, web/src/pico/flex.scss
Screenshots:
**CPU Emulator**
x0 screen:
x1 screen:
x2 screen:
**VM Emulator**
x0 screen:
x1 screen:
x2 screen:
=> Add different layouts for different screen scales

simulator/src/chip/builtins/computer/computer.tsx
The address pin of the ROM32K chip was 16-bit wide (instead of 15), causing valid Computer.hdl implementations to not compile.
=> Fix builtin ROM32K input pin width

simulator/src/languages/asm.test.ts, simulator/src/languages/asm.ts, simulator/src/languages/grammars/asm.ohm, simulator/src/languages/grammars/asm.ohm.js, web/src/pages/asm.tsx
Before the change, the assembler would allow for 2 instructions to be on the same line,
and would accept spaces between instruction parts, i.e `@ 2`
=> Fix asm parsing bugs

simulator/src/languages/asm.ts, simulator/src/languages/grammars/asm.ohm, simulator/src/languages/grammars/asm.ohm.js
This is the intended form as described in the book,
but the desktop simulator has it the other way around,
so Shimon proposed we support both forms.
=> Allow DM,ADM as assembly destinations

web/src/pico/icon.scss
A recent change aimed at making the header scrollable on mobile resulted in the tooltips being cropped.
=> Fix header tooltip being cropped

simulator/src/chip/builder.ts, simulator/src/chip/chip.test.ts, simulator/src/chip/chip.ts
This is a narrower / smaller approach than #328, without needing to pull in an entire second graph, as Chips already implement the graph. This makes the topo insertion sort correctly handle internal/external/before/after pins. The test is the same as from #328.
Closes #327
=> Chip: insertion sort accounts for both incoming and outgoing edges.

simulator/src/cpu/cpu.test.ts, simulator/src/cpu/cpu.ts
An alternative to #340 that doesn't break the built-in CPU chip implementation.
Fixes #337.
=> Write to memory before second ALU computation on tock

components/src/stores/chip.store.ts
Bug report from Coursera forum:
Explanation: the removed reset caused the `useEffect` in https://github.com/nand2tetris/web-ide/blob/main/web/src/pages/chip.tsx#L94 to loop indefinitely.
=> Bug fix: builtin only chips keep resetting on firefox

web/src/pico/pico.scss, web/src/shell/file_select.tsx
Closes #359 
File picker will now look like this in the example provided in the issue:
=> Fix color shceme of file picker in dark theme

web/src/shell/Monaco.tsx, web/src/shell/editor.tsx
1. In Monaco.tsx, useMonaco is having some issues with cancelled promises. Switch to monaco being a useRef and set in onMount.
2. In Editor.rsx, use react lazy rather than hand rolling the import, and use a Suspense guard for loading.
=> Better handle lazy loading monaco

simulator/src/languages/grammars/hdl.ohm, simulator/src/languages/grammars/hdl.ohm.js, simulator/src/languages/hdl.test.ts
This better matches the book specification: "any sequence of letters or digits not starting with a digit", and is compatible with the desktop simulator and Coursera graders.
=> Forbid underscores in HDL identifiers

web/public/index.html
It seems like the IDE doesn't update even after deployment, and only updates when you clear the browser cache.
Hopefully this will solve the issue.
([Source](https://github.com/orgs/community/discussions/19713))
=> Add meta tags to disable page caching by browser

projects/src/project_07/11_simple_add.ts, projects/src/project_07/12_stack_test.ts, projects/src/project_07/21_basic_test.ts, projects/src/project_07/22_pointer_test.ts, projects/src/project_07/23_static_test.ts, projects/src/project_08/11_basic_loop.ts, projects/src/project_08/12_fibonacci_series.ts, projects/src/project_08/20_simple_function.ts, projects/src/project_08/21_nested_call.ts, projects/src/project_08/22_fibonacci_element.ts, projects/src/project_08/23_statics_test.ts
These are the files generated by the student's VM translator and will have to be loaded manually.
=> Remove load commands from asm tests of project 7,8

simulator/src/chip/builder.test.ts, simulator/src/chip/builder.ts, simulator/src/chip/chip.ts
#401 didn't cover the case where the loop spanned over multiple parts.
For example:
```
CHIP Not {
IN in;
OUT out;
PARTS:
Nand(a=in, b=b, out=c);
Nand(a=in, b=c, out=b);
}
```
Which as it stands still causes a crash.
=> Report error when chip parts have a loop

simulator/src/languages/grammars/asm.ohm, simulator/src/languages/grammars/asm.ohm.js, simulator/src/languages/grammars/base.ohm, simulator/src/languages/grammars/base.ohm.js
=> Allow colon in ASM symbols

web/src/pages/compiler.tsx, web/src/pico/pico.scss
=> Improve compiler error tab color for dark theme

simulator/src/jack/compiler.ts, simulator/src/vm/builtins.ts, simulator/src/vm/vm.ts
=> Fix issues with overriding OS classes

simulator/src/vm/builtins.ts, simulator/src/vm/vm.ts
This adds no-op init functions into the VM Emulator. These initializations are already performed by the simulator builtins in the TypeScript implementation. This exposes them for correctness when Jack compilers emit them as part of the sys.jack and OS bootstrap. 
Closes #438
=> Add init functions to OS and call them in Sys.init

projects/src/samples/project_11/average.ts, projects/src/samples/project_11/complex_arrays.ts, projects/src/samples/project_11/convert_to_bin.ts, projects/src/samples/project_11/pong/ball.ts, projects/src/samples/project_11/pong/bat.ts, projects/src/samples/project_11/pong/pong_game.ts, projects/src/samples/project_11/square/square.ts, projects/src/samples/project_11/square/square_game.ts, simulator/src/jack/compiler.test.ts, simulator/src/jack/compiler.ts
=> Add class name as prefix to VM labels in the compiler

cli/src/index.ts
As I am not using web-ide jack editor because it's slow, I've decided to add cli command to invoke Jack compiler directly
=> Add compile jack comand to cli

web/src/shell/tab.scss
Fixes #451 
the line ` position: absolute !important;` caused the issue.
`disply: none;` achieves the same effect.
=> Fix compiler page offset when having too much tabs

components/src/file_utils.ts, components/src/stores/base.context.ts, components/src/stores/chip.store.ts, projects/src/full.ts, projects/src/reset.ts, web/src/shell/settings.tsx
1. "Select existing folder" resulted in a failure if a folder was already selected.
2. Hardware Simulator: If there were no HDL project directories, the chip menu would still contain the project 1 chips. Choosing them resulted in a file not found error.
=> Fs UI bug fixes

components/src/table.tsx, web/src/pico/pico.scss
=> Fix symbol table text color for dark theme

simulator/src/vm/os/string.ts
The vm call `String.new` now only checks if `size` is negative, so that empty strings work as expected.
=> fix: #498 allow Zero-sized strings in VM.

web/src/shell/settings.tsx
=> Add projects/ download to settings via Drive link

simulator/src/timer.ts
=> Add timer limiter to keep steps per update managable.

projects/src/base.ts
https://github.com/nand2tetris/web-ide/commit/eb5f60496a2490c82e1ac91d4de5943038d42282 broke recommended order for chips projects after project 01 (e.g. 2, 3, 5) and instead alphabetically sorts them.
See 
Correct/Fixed output
=> Update sorting for chips projects

simulator/src/cpu/memory.ts, simulator/src/test/cputst.ts
Added isEmpty() to Memory class
check for ROM.isEmpty() instead of fileLoaded in cputst.step()
=> Fix #523: Cpu emulator test runner doesn't recognize asm from assembler page

web/src/shell/settings.scss, web/src/shell/settings.tsx
currently some of the "buttons" on the settings dialog are actualy <a> with role="button" and as so - have a different style than the other buttons on this menu. This PR adjusts this issue, while adding a new "settings.scss" file for these (and possibly future) settings related styles.
before change -
after change -
=> Adjust width of some buttons on the Settings dialog

simulator/src/vm/os/sys.ts
The Sys.wait instruction used to utilize a simple loop that looped `ms` times. Because the execution speed differs a lot, depending on the computer and browser, the wait instruction didn't seem to wait at all.
I guess, the better solution is, to use a javascript timeout, so the wait time will be consistent in all configurations.
=> fix #495: VM emulator ignores Sys.wait

components/src/stores/vm.store.ts, web/src/pages/vm.tsx
TESTED=Added broken code and confirmed it got hit in test / normal runs.
=> Add error highlighting and keep status when the VM throws.

web/src/shell/test_panel.tsx
As described in issues #543 #565 #551 and #543, using the built-in Mult.tst file always overwrite users' programs in RAM, which makes CPU Emulator completely unusable in project 4. Therefore, I changed loadTest such that:
- It allows users to upload local .cmp and .tst file
Benefits:
- Users can use their .tst file without the problematic `load Mult.asm`
- The current fs-based test loading is maintained
However, it requires users to load .cmp and .tst separately, and `compare-to Mult.cmp` must be removed simultaneously to use local .cmp file.
=> Allow users to upload local .tst and .cmp files in CPU Emulator
