nand2tetris/web-ide

docs/app.js, src/app.ts, src/components/memory.ts, src/components/screen.ts, src/index.html, src/pages/cpu.ts, src/testing/fill.ts
Updated the memory component and cpu page to be slightly more mobile friendly. Tested various viewports out locally - changes look alright.
=> mobile friendly mods

src/components/pinout.ts, src/util/twos.test.ts, src/util/twos.ts
=> Format pins by width #28

src/pages/chip.ts, src/projects/index.ts, src/projects/project_05/01_memory.ts, src/projects/project_05/02_cpu.ts, src/projects/project_05/03_computer.ts, src/projects/project_05/index.ts
=> Project 5 files

src/components/pinout.ts, src/pages/chip.ts
=> UX Chip Page verbiage.

src/simulator/chip/builtins/logic/or.ts
=> Fix outwidth for or16 builtin.

src/simulator/chip/chip.test.ts, src/simulator/chip/chip.ts
=> Ensure appopriate width for output pins.

src/app.ts, src/languages/hdl.test.ts, src/languages/hdl.ts, src/languages/tst.ts, src/pages/chip.ts, src/projects/project_05/01_memory.ts, src/projects/project_05/02_cpu.ts, src/simulator/chip/builtins/computer/computer.ts, src/simulator/chip/builtins/index.ts, src/simulator/chip/builtins/sequential/ram.ts, src/simulator/chip/chip.ts
Groundwork for project 5. All files load and can execute without errors, but tests do fail.
=> Project 5 groundwork

src/components/difftable.tsx, src/pages/chip.tsx
=> Added diff table to clear up room for visualizations

src/components/pinout.test.tsx, src/components/pinout.tsx
=> Use '1/0' instead of 'High/Low'

src/components/pinout.scss
=> Narrow and right-align left column of pinout table.

src/components/chips/keyboard.tsx, src/simulator/chip/builtins/computer/computer.tsx
=> Add Keyboard component

src/components/editor.scss, src/components/editor.tsx, src/languages/base.ts, src/languages/tst.test.ts, src/languages/tst.ts, src/pages/chip.store.ts, src/pages/chip.tsx, src/simulator/tst.test.ts, src/simulator/tst.ts
* Track test instruction line positions in parser
* Track test instruction positions when executing
* Highlight and center instruction lines when stepping through tests
=> Show positions of test instruction lines.

src/components/difftable.tsx, src/components/pinout.scss, src/components/pinout.tsx, src/pages/chip.tsx
* All names are alwyas visible
* All pins are always visible
=> Tighten up pins table

src/components/chips/screen.tsx, src/components/chips/visualizations.tsx, src/components/editor.scss, src/components/editor.tsx, src/components/pico/flex.scss, src/components/pico/pico.scss, src/components/runbar.tsx, src/pages/chip.scss, src/pages/chip.tsx
=> 3-column separately scrolling displays

package-lock.json, package.json, scripts/predeploy.sh, src/components/shell/settings.tsx, src/pages/util.tsx, src/projects/index.ts, src/urls.tsx
* Copy index.html to known pages, allowing ghpages to load /chips etc
* Lazy Load page bundles
=> ghpages links

src/components/pico/virtual_scroll.tsx
=> VScroll handles overflow anchoring itself.

src/components/pico/tooltip.scss, src/components/runbar.tsx
Fixed #128 toolbar placement & chose icons more in line with desktop app.
"Stop on first error" I would like to discuss in #127.
=> Rework Runbar buttons & add bottom tooltip

src/app/components/tab.scss, src/app/pages/chip.scss, src/app/pages/chip.tsx
Test panel now has 3 tabs, for each file!
=> Add tabs for Test panel

components/src/runbar.tsx, components/src/stores/chip.store.ts, package.json
=> Feat/web/testing 152 & 153

components/src/stores/chip.store.ts, package.json, simulator/src/chip/builder.test.ts, simulator/src/chip/builder.ts, simulator/src/chip/builtins/all.test.ts, simulator/src/chip/builtins/index.ts, simulator/src/projects/all.test.ts, simulator/src/projects/runner.ts
When a part for a chip is not a builtin, attempt to load it from the file system.
=> Load chip parts from file system.

components/src/runbar.tsx
=> Modify text on runbar elements.

projects/src/index.ts, projects/src/project_02/06_alu_all.ts, projects/src/project_02/index.ts, simulator/src/chip/builtins/arithmetic/alu.tsx, simulator/src/cpu/alu.test.ts, simulator/src/cpu/alu.ts
https://medium.com/@MadOverlord/14-nand2tetris-opcodes-they-dont-want-you-to-know-about-f3246831d1d1
=> Add 'All ALU' with full opcode functionality

cli/package.json, components/package.json, components/src/stores/chip.store.test.ts, components/src/stores/chip.store.ts, extension/package.json, extension/views/hdl/src/App.tsx, package-lock.json, projects/package.json, runner/package.json, simulator/package.json, simulator/src/tst.ts, web/package.json, web/src/pages/chip.tsx, web/src/shell/editor.tsx
Fixes #165 and an issue with built-in tests not updating UI State
* Adds tests for chip store
* Renames "initialize" method in chip store
* Fixes bug in store where test chips weren't the same as the simulation chip
* Fixes bug with initializing Editor highlight state (which makes always highlight first test instruction work correctly)
=> Bug: highlight and chips

components/src/chips/alu.tsx, components/src/pinout.tsx, simulator/src/cpu/alu.ts
New SVG visualization for the ALU components
Update of the operation symbols to fit to the book (x, y, x+y, etc...)
=> ALU visualization

simulator/src/vm/vm.ts
=> Remove unused BootstrapFor function

web/src/pages/asm.tsx, web/src/shell/editor.tsx
Bug description: the assembler editor would autoscroll to top every time an edit was made.
=> Fix assembler scroll bug

web/public/root.css
picocss just released version 2 which messes up our button sizes
=> Specify picocss version

package-lock.json, web/package.json, web/src/locales.ts, web/src/setupTests.ts
This makes the lingui generated file esm/exports compliant, which will be important for some browsers and bundlers.
=> Use ESM namespace for lingui compile

components/package.json, components/src/chips/alu.tsx, components/src/chips/memory.tsx, components/src/chips/visualizations.tsx, components/src/pinout.tsx, components/src/public/alu.css, components/src/public/pin.css, components/src/stores/chip.store.ts, projects/src/index.ts, projects/src/project_01/00_nand.ts, projects/src/project_03/02_register.ts, projects/src/project_03/03_pc.ts, projects/src/project_05/index.ts, simulator/src/chip/builtins/computer/computer.tsx, simulator/src/chip/builtins/sequential/bit.tsx, web/src/pages/chip.tsx, web/src/pages/cpu.scss, web/src/pages/cpu.tsx, web/src/pages/vm.scss, web/src/pages/vm.tsx, web/src/pico/pico.scss, web/src/shell/test_panel.tsx, web/src/versions.ts
A few more changes as requested by Shimon
=> Hardware simulator and CPU emulator UI changes

components/src/stores/cpu.store.ts, simulator/src/cpu/memory.ts, simulator/src/test/cputst.ts
Since implementing Mult.asm is part of project 4 it seems illogical that it will be loaded by default.
=> Start CPU ROM as empty

components/src/stores/asm.store.ts, web/src/App.context.ts, web/src/pages/asm.scss, web/src/pages/asm.tsx, web/src/pages/cpu.tsx, web/src/pico/pico.scss, web/src/shell/editor.scss, web/src/shell/editor.tsx
UI changes:
1. Move filename from panel header to page title
2. change compare panel title to "Compare Code"
3. Change comparison failure message format
4. lock highlight on comparison failure and color the compare highlight red
=> Assembler UI fixes

web/src/shell/settings.tsx
This dialog now shows up after resetting the files:
=> Move file-reset comfirmation message to a dialog

components/src/stores/asm.store.ts, web/src/pages/asm.scss, web/src/pages/asm.tsx
With symbol table:
Without symbol table:
=> Add toggle for diaplying/hiding symbol table

components/src/chips/keyboard.tsx, web/src/pages/cpu.tsx
Changes to register and keyboard display:
=> Minor CPU emulator UI changes

components/src/chips/screen.tsx, web/src/pages/cpu.tsx, web/src/pages/vm.tsx
https://github.com/nand2tetris/web-ide/assets/498712/5ce393c8-40ee-4cf0-8078-f71ab6300e74
Closes #265
=> Pass scale to Screen to maintain scale when using key to rerender

web/src/pages/chip.tsx
=> Update clock display

web/src/shell/header.tsx
Shimon has requested to change back the user guides to link to the original files so that he could make changes on the fly, at least for the short term.
=> Link directly to original user guide files

simulator/src/languages/grammars/base.ohm, simulator/src/languages/grammars/base.ohm.js, simulator/src/languages/grammars/hdl.ohm, simulator/src/languages/grammars/hdl.ohm.js
=> Allow identifiers to start with dollar or dot

web/src/languages/asm.ts, web/src/languages/base.ts, web/src/languages/cmp.ts, web/src/languages/hdl.ts, web/src/languages/loader.js, web/src/languages/tst.ts, web/src/languages/vm.ts, web/src/shell/Monaco.tsx, web/src/shell/editor.tsx
Part of #305, reduced bundle by ~600kb.
=> Dynamically import and upgrade Monaco

simulator/src/chip/builtins/computer/computer.tsx, simulator/src/chip/chip.test.ts, simulator/src/chip/chip.ts
=> Keep chip parts sorted when wiring.

runner/src/types.ts, simulator/src/vm/vm.test.ts
I believe after this fix all the other PRs should pass
=> Fix imports

components/src/runbar.tsx
=> Change default speed to mid

components/src/chips/screen.tsx
=> Highlight current screen scale

components/src/stores/asm.store.ts, web/src/shell/Monaco.tsx
Fixes #314 and other ASM highlighting issues for windows
=> Change monaco editor EOL to always be LF

web/src/pages/chip.tsx
=> Remove unnecessary recompile calls

simulator/src/cpu/alu.ts, simulator/src/languages/asm.ts, simulator/src/languages/grammars/asm.ohm, simulator/src/languages/grammars/asm.ohm.js, simulator/src/util/asm.ts
=> Improve assembly error reporting

simulator/src/chip/builder.ts, simulator/src/chip/chip.ts, simulator/src/chip/clock.ts
=> Order clock subscriptions according to part order

web/src/shell/header.tsx, web/src/urls.tsx
=> Expose compiler page

web/src/shell/settings.tsx
=> Temporarily hide "Upgrade fs" button in settings

.github/ISSUE_TEMPLATE/bug.yaml, .github/ISSUE_TEMPLATE/feature.yaml
Closes #330 
I'm just now realizing that by "this page" in #330 @Shimon-Schocken meant the bug/feature report form.
(We also want to deploy the compiler nonetheless, but that wasn't what this issue was about)
=> Update bug/feature forms

web/src/pages/compiler.tsx
=> Update compiler tooltips

components/src/chips/keyboard.tsx
=> Consume key press events in emulator

components/src/compare.ts, web/src/shell/editor.scss, web/src/shell/test_panel.tsx
New diff table tab, now separated from the output file tab:
=> Improve test panel diff view

.github/ISSUE_TEMPLATE/bug.yaml, .github/ISSUE_TEMPLATE/feature.yaml
=> Update bug/feature report forms

web/src/pages/asm.tsx, web/src/pages/chip.tsx
=> Replace textual download buttons with icon buttons

web/src/languages/jack.ts
=> Fix jack syntax highlighting for bool/boolean

simulator/src/vm/os/string.ts
=> Handle '-' char correctly in string-int conversions

projects/src/samples/project_11/convert_to_bin.ts, projects/src/samples/project_11/pong/ball.ts, projects/src/samples/project_11/pong/bat.ts, projects/src/samples/project_11/pong/pong_game.ts, projects/src/samples/project_11/square/square.ts, projects/src/samples/project_11/square/square_game.ts, simulator/src/jack/compiler.ts
=> Fix true literal to be -1

web/src/pico/accordion.scss, web/src/shell/panel.tsx
=> Move accordion caret position

components/src/stores/asm.store.ts, components/src/stores/compiler.store.ts, components/src/stores/cpu.store.ts, components/src/stores/vm.store.ts, web/src/App.context.ts, web/src/App.tsx, web/src/Page.context.tsx, web/src/pages/asm.tsx, web/src/pages/chip.tsx, web/src/pages/compiler.tsx, web/src/pages/cpu.tsx, web/src/pages/vm.tsx, web/src/shell/header.tsx, web/src/shell/settings.tsx
A cleaner more maintainable way to handle state preservation IMO.
Fixes #358
=> Preserve vm source when switching tools

components/src/chips/memory.tsx, components/src/runbar.tsx, components/src/stores/asm.store.ts, components/src/stores/chip.store.ts, components/src/stores/cpu.store.ts, components/src/stores/vm.store.ts, web/src/pages/asm.tsx, web/src/pages/chip.tsx, web/src/pages/cpu.tsx, web/src/pages/vm.tsx, web/src/shell/test_panel.tsx
=> Save UI settings when switching between pages

web/src/pages/asm.tsx, web/src/pages/chip.tsx, web/src/pages/vm.tsx, web/src/pico/pico.scss, web/src/shell/panel.tsx
=> Set 'overflow-y: hidden' for editor containers

web/public/bitmap_editor.html
=> Save bitmap editor state in local storage

simulator/src/cpu/memory.ts
=> Fix CPU RAM size

simulator/src/chip/builder.ts, simulator/src/chip/builtins/computer/computer.tsx, simulator/src/chip/builtins/sequential/bit.tsx, simulator/src/chip/builtins/sequential/dff.ts, simulator/src/chip/builtins/sequential/ram.tsx, simulator/src/chip/chip.test.ts, simulator/src/chip/chip.ts
=> Implement topological sort from Java verison

components/src/pin_display.ts, components/src/stores/chip.store.test.ts, components/src/stores/chip.store.ts, simulator/src/chip/builder.ts, simulator/src/chip/builtins/builtinOverrides.ts, simulator/src/chip/builtins/index.ts
Fixes #376.
I couldn't figure out what was wrong with the previous built-in CPU implementation, but at least this is a temporary fix.
=> Replace builtin CPU implementation

components/src/chips/memory.tsx, simulator/src/cpu/memory.ts
=> Display 0 in unused RAM cells

simulator/src/chip/builder.test.ts, simulator/src/chip/builder.ts
=> Check for looping wires when building chip

cli/src/grading.ts, cli/src/index.ts
Possible solution for https://github.com/nand2tetris/web-ide/issues/402
=> Exit with non-zero code if the grade command failed (#402)

web/src/pages/compiler.tsx
=> Add message when loading empty folder to compiler

web/src/shell/Monaco.tsx
=> Remeasure editor font when needed

web/src/pico/pico.scss, web/src/shell/editor.scss, web/src/shell/test_panel.tsx
=> Improve test diff colors for dark theme

simulator/src/languages/grammars/tst.ohm, simulator/src/languages/grammars/tst.ohm.js, simulator/src/languages/tst.ts, simulator/src/test/builder.ts, simulator/src/test/cputst.ts, web/src/languages/tst.ts
=> Implement resetRam test command

web/src/pages/vm.tsx
=> Reset VM file input after upload

cli/src/grading.ts
=> Support for new project file structure in CLI

web/src/pages/vm.tsx
Fixes #531 
TESTED=Opened FibonacciElement / my Project 11 Square project which have multiple files / no tests. They now load correctly and run on my MacOS machine.
=> Fix loading a directory of .vm files and recover from not having Test.
